### ISSUE TITLE
float clip crash in mt_edge

### ISSUE THREAD

**Issue by realfinder** [pinterf/masktools#12]
colorbars()
converttoyv12
convertbits(32)
mt_edge(thY1=0,thY2=255,mode="min/max",U=1,V=1)
convertbits(8)

**Comment by pinterf** [comment]
Could not reproduce, I have tried even with different SetMaxCPU values, and differently sized clip (ColorBarsHD)

**Comment by realfinder** [comment]
ok, using 
![image](https://user-images.githubusercontent.com/2512153/89449812-4acdf580-d762-11ea-954f-ed874d928f56.png)

with x64 crash with 
![image](https://user-images.githubusercontent.com/2512153/89450121-b57f3100-d762-11ea-8390-df0ab2521cad.png)

but x86 fine! also with x64 in 
![image](https://user-images.githubusercontent.com/2512153/89450215-e19ab200-d762-11ea-8fa9-de2342e52a32.png)

also fine

**Comment by pinterf** [comment]
"Illegal instruction" is important. Not the usual overaddressing C0000005.
That processor knows AVX but not AVX2. I have to find an AVX2 instruction.
Can you test it with SetMaxCPU("SSE4.1"), I suppose the error is gone then?

**Comment by realfinder** [comment]
yes with SetMaxCPU("SSE4.1") seems work fine

**Comment by pinterf** [comment]
Found, mt_edge module could use AVX2 instructions. Also mt_logic was suspicious. Usually 32 bit float SIMD requires only AVX but the optimizer may change some instructions into AVX2. Since the full build takes 20-30 minutes (did I say how I like masktools with thousand dll versions? :) ), I'll leave the machine work and will prepare the new pack tomorrow.

**Comment by pinterf** [comment]
New build, fix of illegal instruction, please try if it is O.K.
https://drive.google.com/file/d/1dGh7deLE9mvUZtCYcrqxa4OTaWzpOEx8/view?usp=sharing

**Comment by realfinder** [comment]
yes, that work, thanks
