### ISSUE TITLE
mt_merge no error but just crash

### ISSUE THREAD

**Issue by TbtBI** [pinterf/masktools#16]
Hi,

When mask clip has only one plane and mt_merge(x, y, z, u=3,v=3) is used there is no error that mask should have chroma planes for u=v=3 but mt_merge just crash.

**Comment by realfinder** [comment]
this work fine for me
```
ColorBars(width=640, height=480, pixel_type="yv12")
converttoy8
mt_merge(last, last, last, u=3,v=3)
```

**Comment by pinterf** [comment]
Well, seeing the code, it does not crash when the input clip is greyscale.
```
     // PF: for greyscale: graceful fallback to chromaless operation
      if (plane_counts[C] == 1) {
        use_luma = false;
        operators[1] = operators[2] = operators[3] = NONE;
      }
```
When the mask clip is greyscale, input clip is not greyscale and luma is false, well, this case is not covered.

**Comment by pinterf** [comment]
What should be the proper behaviour if luma=false (default) but only a greyscale mask is provided? I suppose it should act as luma=true automatically.
EDIT: no. Because - as a rule - luma=true implies chroma processing as well, and this may not be what we want.
Next proposal: when providing a greyscale mask + clips are not greyscale + luma==false, then error message is thrown if mode u or v is set to 'process', 
EDIT2: what about this one:
Error: "mask clip is greyscale and 'u' or 'v' or 'a' processing is set with luma=false"

**Comment by realfinder** [comment]
> 
> 
> Next proposal: when providing a greyscale mask + clips are not greyscale + luma==false, then error message is thrown if mode u or v is set to 'process',
> EDIT2: what about this one:
> Error: "mask clip is greyscale and 'u' or 'v' or 'a' processing is set with luma=false"

seems ok

off-topic but can you please take a look at the last 2 issues since about 2 months here? https://github.com/pinterf/TIVTC/issues

**Comment by pinterf** [comment]
off - sorry, no time for those in the _near_ future

**Comment by TbtBI** [comment]
> EDIT2: what about this one:
> Error: "mask clip is greyscale and 'u' or 'v' or 'a' processing is set with luma=false"

It looks ok to me too.

**Comment by pinterf** [comment]
O.K., fixed in https://github.com/pinterf/masktools/commit/041146640e6a0f3a547f8237d74b4c7a34f40834

**Comment by TbtBI** [comment]
Thanks.
